### ISSUE TITLE
No fork indication which is required in GNU/GPLv2

### ISSUE THREAD

**Issue by pgronkievitz** [pop-os/gnome-shell-extension-multi-monitors#3]
According to [TLDR Legal](https://tldrlegal.com/license/gnu-general-public-license-v2) (I'm not a lawyer anyway) copyright has to be included in redistributed code.

**Comment by Bananaman** [comment]
And the upstream that this was cloned from is actively developed:

https://github.com/spin83/multi-monitors-add-on

Why even clone it? Contribute to upstream instead... :/

**Comment by jackpot51** [comment]
@pgronkievitz any copyright that was present in the upstream code, is present in this repository
@Bananaman this "fork" is only to perform packaging and change default settings for Pop!_OS, not to develop any new features which would certainly be contributed upstream.

**Comment by Bananaman** [comment]
@jackpot51 Okay. Good. :-)

**Comment by Jheengut** [comment]
Is this not the copyright ::

https://github.com/pop-os/gnome-shell-extension-multi-monitors/blob/master_hirsute/LICENSE
